backend:
  name: github
  repo: iteam-software/bonanza-creek-ranch-com
  branch: main

media_folder: static/assets
public_folder: /assets

media_library:
  name: cloudinary
  config:
    cloud_name: dtr82nmhr
    api_key: 318749173396793
    max_files: 100

collections:
  - name: sets
    label: Sets
    folder: sets
    create: true
    fields:
      - { name: title, label: Title }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - {
          name: gallery,
          label: Gallery,
          widget: image,
          media_library: { config: { multiple: true } },
        }
      - { name: body, label: Body, widget: markdown }
