backend:
  name: github,
  repo: iteam-consulting/bonanza-creek-ranch-com

media_folder: static/assets
public_folder: /assets

collections:
  - name: sets
    label: Sets
    folder: sets
    create: true
    fields:
      - { name: title, label: Title }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - {
          name: gallery,
          label: Gallery,
          widget: list,
          field: { name: image, label: Image, widget: image },
        }
      - { name: body, label: Body, widget: markdown }
